# Server related settings
address: 192.168.1.2
port: 8043
auth: true
tls: false
#cert: cert.pem
#key: key.pem

# CORS configuration
cors:
  enabled: true
  credentials: true
  allowed_headers:
    - Depth
    - Authorization
    - Content-Type
  allowed_hosts:
    - "*"
  allowed_methods:
    - GET
    - PUT
    - POST
    - PATCH
    - DELETE
    - OPTIONS
    - PROPFIND
    - MKCOL
    - LOCK
    - PROPPATCH
    - COPY
    - MOVE
    - UNLOCK
  exposed_headers:
    - Content-Length
    - Content-Range

# The password can be either plaintext or bcrypt hash (https://bcrypt-generator.com/)
# In case of bcrypt hash set it like this: "{bcrypt} encrypted password"
users:
  - username: admin
    password: admin123
    scopes:
      - root: /srv/dav
        alias: /
        allow_w: true
      - root: /srv/files
        alias: files
        rules:
          - path: /Downloads
            allow_w: true
  - username: owncloud
    password: owncloud123
    scopes:
      - root: /srv/dav/Photos
        alias: remote.php/webdav
        allow_w: true
      - root: /srv/dav/Photos
        alias: remote.php/dav/files/owncloud
        allow_w: true
      - root: /srv/dav/Photos
        alias: /index.php/core/preview.png
        owncloud_preview: true
